
import Project.ConnectionProvider;
import java.sql.Connection;
import javax.swing.*;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Abi
 */
public class displayservices extends javax.swing.JFrame {

    /**
     * Creates new form displayservices
     */
    public displayservices() {
        initComponents();
        
        loadcombo();
    }
private void loadcombo() {
        // Example services with prices
        jComboBox1.addItem("Pending");
        jComboBox1.addItem("In Progress");
        jComboBox1.addItem("Completed");
        // Add more services as needed
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Service ID", "Customer ID", "Request date", "Service", "Phone no", "Status"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 1210, 400));

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jButton1.setText("DISPLAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 650, 130, 50));

        jButton2.setBackground(new java.awt.Color(51, 204, 255));
        jButton2.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 650, 130, 50));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel1.setText("SERVICE REQUESTS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 260, -1));

        jButton3.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeicon.png"))); // NOI18N
        jButton3.setText("HOME ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 80, 140, 40));

        jButton4.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        jButton4.setText("Updatestatus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 580, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item" }));
        jComboBox1.setToolTipText("");
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 580, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DISPLAY.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -50, 1580, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       {
     try
        {
        Connection con=ConnectionProvider.getCon();
        Statement st=con.createStatement();
        //st.executeUpdate("insert into customer values('"+customer+"','"+cname+"','"+cemail+"','"+cphoneno+"','"+caddress+"')");
        java.sql.ResultSet rs=st.executeQuery("select * from newserv n inner join customers c on n.custid=c.idcustomer");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        while(rs.next()){
            Object[] row=
            {
                rs.getString("requestid"),rs.getString("custid"),rs.getString("requestdate"),rs.getString("servicename"),rs.getString("phoneno"),rs.getString("status")};
                model.addRow(row);
        }
        }
catch (Exception e) { 
        javax.swing.JOptionPane.showMessageDialog(null, "Error updating customer: " + e.getMessage());
        setVisible(false);
        
    }                            

    }//GEN-LAST:event_jButton1ActionPerformed
 /*private void loadservicerequest(){
     try
        {
        Connection con=ConnectionProvider.getCon();
        Statement st=con.createStatement();
        //st.executeUpdate("insert into customer values('"+customer+"','"+cname+"','"+cemail+"','"+cphoneno+"','"+caddress+"')");
        java.sql.ResultSet rs=st.executeQuery("select * from newserv n inner join customer c on n.custid=c.idcustomer");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        while(rs.next()){
            Object[] row=
            {
                rs.getString("requestid"),rs.getString("custid"),rs.getString("requestdate"),rs.getString("servicename"),rs.getString("phoneno"),rs.getString("status")};
                model.addRow(row);
        }
        }
catch (Exception e) { 
        javax.swing.JOptionPane.showMessageDialog(null, "Error updating customer: " + e.getMessage());
        setVisible(false);
        new displayservices().setVisible(true);
    }  
 }*/
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Home2().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
private void sendNotificationToCustomer(String requestId, String newStatus) {
    try {
        // Fetch the customer ID based on the requestId
        String query = "SELECT custid FROM newserv WHERE requestid = ?";
        Connection con = ConnectionProvider.getCon(); 
        PreparedStatement pstmt = con.prepareStatement(query);
        pstmt.setString(1, requestId);
        ResultSet rs = pstmt.executeQuery();
        
        if (rs.next()) {
            String customerId = rs.getString("custid");
            String notificationMessage = "Your service request #" + requestId + " has been updated to " + newStatus;
            
            // Insert the notification into the notifications table
            String insertNotificationQuery = "INSERT INTO notifications (cid, message,created_at) VALUES (?, ?,CURRENT_TIMESTAMP)";
            PreparedStatement insertPstmt = con.prepareStatement(insertNotificationQuery);
            insertPstmt.setString(1, customerId);
            insertPstmt.setString(2, notificationMessage);
            insertPstmt.executeUpdate();
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                                       
    {                                         
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow != -1) {
        String requestId = (String) jTable1.getValueAt(selectedRow, 0); // Get the request ID
        String newStatus = (String) jComboBox1.getSelectedItem(); // Get the selected status
        
        try {
            Connection con = ConnectionProvider.getCon();
            String updateQuery = "UPDATE newserv SET status = ? WHERE requestid = ?";
            PreparedStatement pstmt = con.prepareStatement(updateQuery);
            pstmt.setString(1, newStatus);
            pstmt.setString(2, requestId);
            pstmt.executeUpdate();
            if (newStatus.equals("Completed")) {
                String updateCompletionQuery = "UPDATE newserv SET completion_date = NOW() WHERE requestid = ?";
                PreparedStatement completionStmt = con.prepareStatement(updateCompletionQuery);
                completionStmt.setString(1, requestId);
                completionStmt.executeUpdate();
            }
            
            // Send a notification to the customer
            sendNotificationToCustomer(requestId, newStatus);
            
            JOptionPane.showMessageDialog(this, "Status updated successfully!");
            jButton1ActionPerformed(evt); // Refresh the table after update
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error updating status: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a service request to update.");
    }
}

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(displayservices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(displayservices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(displayservices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(displayservices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new displayservices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
