import Project.ConnectionProvider;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Abi
 */
public class payment extends javax.swing.JFrame {
    private String servicereqid;
    private String customerId;
    private String selectedService;

    /**
     * Creates new form payment
     */
    public payment(String servicereqid,String customerId,String selectedService) {
        this.servicereqid=servicereqid;
        this.customerId = customerId;
        this.selectedService = selectedService;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        jLabel1.setText("PAYMENT PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 360, -1));

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jButton1.setText("PAY NOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 150, 40));

        jButton2.setBackground(new java.awt.Color(51, 204, 255));
        jButton2.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 550, 120, 40));

        jButton3.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 180, -1, 50));

        jLabel3.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N
        jLabel3.setText("Secure Payment: Your information is encrypted and protected. \n  ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locker.png"))); // NOI18N
        jLabel2.setText(" Privacy Guarantee: We never share your payment details with anyone.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jLabel4.setText("PROCEED TO PAY!!");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, -1, -1));

        jLabel5.setText("By clicking Pay Now, you agree to our Terms & Conditions and Privacy Policy.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/detpage.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String customerName = "";
        String customerPhone = "";
        String amount = getRandomAmountFromService(selectedService); // Get random amount based on selected service
        String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
        String time = new SimpleDateFormat("HH:mm:ss").format(new Date());

        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            String query = "SELECT name, phoneno FROM customers WHERE idcustomer = '" + customerId + "'";
            ResultSet rs = st.executeQuery(query);
            if (rs.next()) {
                customerName = rs.getString("name");
                customerPhone = rs.getString("phoneno");
            } else {
                JOptionPane.showMessageDialog(null, "Customer not found.");
                return;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error retrieving customer details: " + e.getMessage());
            return;
        }

        // Generate PDF receipt
        /*generateReceipt(customerName, customerPhone, amount, date, time);

        JOptionPane.showMessageDialog(null, "Payment successful for Service Request ID: " + servicereqid);
        new pdfex(servicereqid,customerId,selectedService).setVisible(true); // Assuming pdfex is another JFrame for displaying something
        setVisible(false);*/
        showBillDialog(customerName, customerPhone, amount, date, time);
    }
    private void showBillDialog(String customerName, String customerPhone, String amount, String date, String time) {
        JDialog billDialog = new JDialog(this, "Payment Bill", true);
        billDialog.setSize(500, 600);
        billDialog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        billDialog.setLocationRelativeTo(this);

        JTextArea jTextArea1 = new JTextArea();
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 16));
        jTextArea1.setText(
            "Service Request Receipt\n" +
            "====================================\n" +
            "Customer Name: " + customerName + "\n" +
            "Customer Phone: " + customerPhone + "\n" +
            "Service Request ID: " + servicereqid + "\n" +
            "Amount Paid: " + amount + "\n" +
            "Date: " + date + "\n" +
            "Time: " + time + "\n" +
            "====================================\n" +
            "Thank you for your business!"
        );

        JScrollPane jscrollPane1 = new JScrollPane(jTextArea1);
        billDialog.add(jscrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 440, 350));

        JCheckBox jCheckBox1 = new JCheckBox("I confirm the payment");
        billDialog.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 440, 30));

        JButton jButton1 = new JButton("Confirm");
        jButton1.setEnabled(false);
        billDialog.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 120, 40));

        jCheckBox1.addActionListener(e -> {
            jButton1.setEnabled(jCheckBox1.isSelected());
        });

        jButton1.addActionListener(e -> {
            generateReceipt(customerName, customerPhone, amount, date, time);
            JOptionPane.showMessageDialog(this, "Payment successful and Receipt saved!");
            billDialog.dispose();
            new pdfex(servicereqid, customerId, selectedService).setVisible(true);
            setVisible(false);
        });

        billDialog.setVisible(true);
    }

    private String getRandomAmountFromService(String service) {
        // Example service format: "Laptop Repair Services - ₹2,000 to ₹10,000"
        String[] parts = service.split(" - ₹");
        if (parts.length < 2) {
            return "₹0"; // Default amount if parsing fails
        }

        String[] range = parts[1].split(" to ");
        if (range.length < 2) {
            return "₹0"; // Default amount if parsing fails
         // Default amount if parsing fails
    }
        // Parse the minimum and maximum amounts
        /*int minAmount = Integer.parseInt(range[0].replace(",", "").trim());
        int maxAmount = Integer.parseInt(range[1].replace(",", "").trim());

        // Generate a random amount within the specified range
        Random random = new Random();
        int randomAmount = random.nextInt((maxAmount - minAmount) + 1) + minAmount;

        return "₹" + randomAmount; // Return the amount as a string with currency symbol
    }*/
try {
        // Parse the minimum and maximum amounts after removing the currency symbol
        int minAmount = Integer.parseInt(range[0].replaceAll("[^0-9]", ""));
        int maxAmount = Integer.parseInt(range[1].replaceAll("[^0-9]", ""));

        // Generate a random amount within the specified range
        Random random = new Random();
        int randomAmount = random.nextInt((maxAmount - minAmount) + 1) + minAmount;

        return "₹" + randomAmount; // Return the amount as a string with currency symbol
    } catch (NumberFormatException e) {
        return "₹0"; // Default value in case of an error
    }
    }
    private void generateReceipt(String customerName, String customerPhone, String amount, String date, String time) {
        // Define the path where the PDF will be saved
        String pdfPath =  System.getProperty("user.home") + "/Downloads/ServiceRequestReceipt_" + servicereqid + ".pdf";

        // Create a PDF document
        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream(pdfPath));
            document.open();

            // Add content to the PDF
            document.add(new Paragraph("Service Request Receipt"));
            document.add(new Paragraph("===================================="));
            document.add(new Paragraph("Customer Name: " + customerName));
            document.add(new Paragraph("Customer Phone: " + customerPhone));
            document.add(new Paragraph("Service Request ID: " + servicereqid));
            document.add(new Paragraph("Amount Paid: " + amount));
            document.add(new Paragraph("Date: " + date));
            document.add(new Paragraph("Time: " + time));
            document.add(new Paragraph("===================================="));
            document.add(new Paragraph("Thank you for your business!"));

            // Close the document
            document.close();
            //JOptionPane.showMessageDialog(null, "Receipt generated successfully: " + pdfPath);
        } catch (DocumentException | IOException e) {
            JOptionPane.showMessageDialog(null, "Error generating receipt: " + e.getMessage());
        }
    

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new servicerequest(customerId).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
