/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package service.management;
/*import java.sql.Connection;

import java.sql.PreparedStatement;

import java.sql.ResultSet;

import javax.swing.JOptionPane;

import Project.ConnectionProvider;

import com.itextpdf.text.Document;

import com.itextpdf.text.DocumentException;

import com.itextpdf.text.pdf.PdfWriter;

import com.itextpdf.text.Paragraph;

import java.io.FileOutputStream;

import java.io.IOException;
import java.sql.SQLException;
import com.itextpdf.text.pdf.PdfPTable;

import java.util.Date;

import java.text.SimpleDateFormat;
 

/**
 *
 * @author Abi
 */
public class pdfex extends javax.swing.JFrame {
    private String serviceRequestId;
    private String customerId;
    private String selectedService;
    /**
     * Creates new form pdfex
     */
    public pdfex(String servicereqid, String customerId, String selectedService) {
        this.serviceRequestId = serviceRequestId;
        this.customerId = customerId;
        this.selectedService = selectedService;
        initComponents();
        jLabel1.setText("Payment Successful!");
        jLabel2.setText("Your receipt has been saved.");
        jLabel3.setText("Service Request ID: " + servicereqid);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 126, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 37, -1));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 37, -1));

        jButton1.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jButton1.setText("BACK");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 100, -1, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DISPLAY.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
        /*try (PDDocument document = new PDDocument()) {
            PDPage page = new PDPage();
            document.addPage(page);

            try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
                //contentStream.setFont(PDType1Font.JUICE, 12);
                contentStream.beginText();
                contentStream.newLineAtOffset(100, 700);
                contentStream.showText("Payment Receipt");
                contentStream.newLineAtOffset(0, -20);
                contentStream.showText("Customer Name: " + customerName);
                contentStream.newLineAtOffset(0, -20);
                contentStream.showText("Customer ID: " + customerId);
                contentStream.newLineAtOffset(0, -20);
                contentStream.showText("Total Price: $" + totalPrice);
                contentStream.newLineAtOffset(0, -20);
                contentStream.showText("Date: " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()));
                contentStream.endText();
            }

            document.save("PaymentReceipt.pdf");
            System.out.println("PDF created successfully!");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }*/
     /*private void generatePdf() {
        try {
            // Specify the file path where the PDF will be saved
            String id=UserSession.getCustomerId();
            String filePath = "D:\\service_pdf"+id+"_"+System.currentTimeMillis()+".pdf";// You can customize the path
            //PdfWriter writer = new PdfWriter(filePath);
            //PdfDocument pdf = new PdfDocument(writer);
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(filePath));
            document.open();



            // Add content to the PDF
            document.add(new Paragraph("Service Request ID: " + serviceRequestId));
            document.add(new Paragraph("Customer ID: " + customerId));
            document.add(new Paragraph("Selected Service: " + selectedService));
            document.add(new Paragraph("Thank you for your payment!"));

            document.close();
            JOptionPane.showMessageDialog(this, "PDF generated successfully: " + filePath);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error generating PDF: " + ex.getMessage());
        }
     }
   
    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pdfex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pdfex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pdfex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pdfex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       //java.awt.EventQueue.invokeLater(() -> {
          // new pdfex(serviceRequestId,customerId,selectedService).setVisible(true);
        //});
               
    //}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
